key = "YOUR SCHOOLOGY KEY HERE"        # Schoology API Key
secret = "YOUR SCHOOLOGY SECRET HERE"  # Schoology API Secret
limit = 200                            # Item Limit for one request (Maximum is 200, not reccomended to change this)